<header>
        <div class="navbar">
            <div class="logo">
                <a href="./index.html">Microself</a>
            </div>
            <div class="menu">
                <a href="./index.html">Home</a>
                <a href="./jobs.html">Career</a>
                <a href="./apply.html">Apply</a>
                <a href="./about.html">About</a>
            </div>
        </div>
</header>